apiVersion: v1
kind: Service
metadata:
  name: devops-taskboard-service
  labels:
    app: devops-taskboard
spec:
  type: NodePort
  selector:
    app: devops-taskboard
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
